### ISSUE TITLE
Create pull request comment when preview available

### ISSUE THREAD

**Issue by vipulgupta2048** [product-os/docusaurus-theme#39]
To gain parity with GitHub actions on Handbook, we need to add a preview URL message to PR similar to https://github.com/balenaltd/handbook/pull/52#issuecomment-1344153371

From: https://github.com/balenaltd/handbook/blob/main/.github/actions/publish/action.yml

```
    - name: Create pull request comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: gh-preview
        GITHUB_TOKEN: ${{ fromJSON(inputs.secrets).FLOWZONE_TOKEN }}
        message: |
          :rocket: Deployed ${{ github.repository }}@${{ github.event.pull_request.head.sha }} to ${{ env.published_url }}

```

Also, investigate
- Does Cloudflare have a limit on previews being created? Or are they going to be unlimited? If it is the latter then we won't need a way to clean our old GitHub previews.
